In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
np.linalg.det(A)

-9.51619735392994e-16

In [11]:
A = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
B = np.array([[1,1],[1,1]])
C = np.array([[1,2],[3,4]])

In [12]:
np.linalg.det(A), np.linalg.det(B), np.linalg.det(C) 

(4.0, 0.0, -2.0000000000000004)

In [13]:
np.trace(A), np.trace(B), np.trace(C)

(6, 2, 5)

In [26]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]  # 'CRIM', 'NOX', 'RM', 'AGE'
b = y[:4]

In [15]:
np.dot(A,b)

array([2417.60498, 2868.85454, 2300.84486, 1783.22028])

In [18]:
A.shape

(4, 4)

In [21]:
b.shape

(4,)

In [20]:
np.dot(b,A)

array([2.769697e+00, 5.461390e+01, 7.795463e+02, 6.918930e+03])

In [22]:
X.shape

(506, 13)

In [23]:
y.shape

(506,)

In [25]:
w = np.dot(np.linalg.inv(A),b)
w

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

In [42]:
w1, resid, rank, s = np.linalg.lstsq(X, y, rcond=None)
w1

array([-9.16297843e-02,  4.86751203e-02, -3.77930006e-03,  2.85636751e+00,
       -2.88077933e+00,  5.92521432e+00, -7.22447929e-03, -9.67995240e-01,
        1.70443393e-01, -9.38925373e-03, -3.92425680e-01,  1.49832102e-02,
       -4.16972624e-01])

In [38]:
w1[0], w1[4], w1[5], w1[6]

(-0.0916297843121869,
 -2.8807793263209094,
 5.925214318082783,
 -0.0072244792886887454)

In [43]:
np.linalg.norm(np.dot(X,w1))**2

287395.1226543055