##### Numpy - make
- array
- reshape
- index
- zeros
- ones
- eye
- like(치환)
- empty(비어있는 행렬 만들기)
- arrange( = range. 속도가 더 빠름)
- linspace, logspace(어떤 데이터가 있을 때 자를 때 llinspace랑 분할. logspace로 분할)
- random: rand, randn
- stack, concat (배열들을 합치는 방법)
- split
- sort

##### array
- ndim: 행렬의 차원
- shape: 행렬의 모양

In [3]:
import numpy as np

In [4]:
# 1차원 배열
array = np.array([0,1,2,3])
print(type(array),array)

<class 'numpy.ndarray'> [0 1 2 3]


In [5]:
# 2차원 배열
array = np.array([[0,1],[1,2],[2,3]])
print(array)

[[0 1]
 [1 2]
 [2 3]]


In [7]:
# 3차원 배열
array = np.array([
    [[0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]],
    
    [[0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]],

])
print(array)
print(array.ndim, array.shape) #2,3,4 중에 마지막 숫자가 가장 안 쪽 갯수 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
3 (2, 3, 4)


##### reshape
 - 행렬의 모양을 바꿀 수 있음

In [8]:
na = np.array(range(1,9))
na

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
na.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
np.reshape(na, (4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
rna = np.reshape(na, (4,2))
rna

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
# 전치행렬
rna.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [13]:
rna.T, rna.T.shape

(array([[1, 3, 5, 7],
        [2, 4, 6, 8]]), (2, 4))

##### index
- 행렬의 특정 위치 값을 가져오기
- 행렬 자르기

In [14]:
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [15]:
print(array[1][1][2]) #1번째(우리의 2번째), 1번째(우리의 2번째), 2번쨰(우리의3번째)

6


In [16]:
print(array[1, 1, 2])

6


In [18]:
# 행렬 자르기
result = array[1:,1:,2:]
result

array([[[ 6,  7],
        [10, 11]]])

In [19]:
array[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
array.ndim, array[0].ndim, array[0][1].ndim # 하나를 가져올 때마다 차원이 하나씩 줄어듦

(3, 2, 1)

In [24]:
# 데이터 수정
data = np.array(range(5))
data

array([0, 1, 2, 3, 4])

In [25]:
data[2]

2

In [27]:
data[2] = 0 # 리스트랑 비슷
data

array([0, 1, 0, 3, 4])

In [28]:
data[3:] = 2
data

array([0, 1, 0, 2, 2])

In [30]:
# 2차원 행렬 데이터 바꾸기
data = np.array([range(3), range(3,6)])
data

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
data[1:,1:] = 10
data

array([[ 0,  1,  2],
       [ 3, 10, 10]])

##### zeros
- 행렬을 만들고 안에 0으로 채워 넣음
- default 값이 float

In [32]:
z = np.zeros(5) #float으로 생성
z

array([0., 0., 0., 0., 0.])

In [34]:
z = np.zeros(5, dtype=int) #이렇게 type을 바꿀 수 있음
z

array([0, 0, 0, 0, 0])

In [37]:
# 2차원
z = np.zeros((2,3), dtype=int)
z

array([[0, 0, 0],
       [0, 0, 0]])

In [47]:
z = np.zeros((2,3,4), dtype=int)
z

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

##### ones
- 행렬을 만들고 1로 채움

In [42]:
one = np.ones((2,3,4), dtype = int)
one

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

##### eye
- 단위 행렬 데이터를 만듦

In [45]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

##### like
- 행렬 안에 있는 모든 데이터를 0이나 1로 바꿀 수 있음

In [48]:
z

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [49]:
np.ones_like(z)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [50]:
np.zeros_like(one)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

##### empty
- 빈 행렬 데이터를 만든다
- 안에 어떤 데이터가 들어갈지 알 수 없음(그때그때 달라요)

In [51]:
np.empty((5,5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
np.empty((2,3))

array([[5.83e-322, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000]])

##### arange
- range와 사용법 같음
- 하지만 큰데이터를 만들 때 속도가 더 빠름

In [54]:
1E6

1000000.0

In [56]:
size = int(1E6)
size

1000000

In [58]:
%timeit for x in range(size): x ** 2
%timeit for x in np.arange(size): x ** 2

1.28 s ± 140 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
558 ms ± 53 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [59]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [60]:
np.arange(2, 10, 3)

array([2, 5, 8])

In [61]:
##### linspace, logspace

In [62]:
np.linspace(0,100,3)

array([  0.,  50., 100.])

In [63]:
np.linspace(0,100,4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [64]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [65]:
# log10(x1)=2, log10(x2) = 3, log10(x3)=4
# x1:100, x2:1000, x3:10000
np.logspace(2,4,3)

array([  100.,  1000., 10000.])

In [67]:
# 2, 2.5, 3
# log10(x1)=2, log10(x2) = 2.5, log10(x3)=3
# x1 = 10**2, x2 = 10**2.5, x3 = 10**3
np.logspace(2,3,3)

array([ 100.        ,  316.22776602, 1000.        ])

In [69]:
10**2, 10**2.5, 10**3

(100, 316.22776601683796, 1000)

##### random
- seed : 랜덤값을 결정해주는 값(seed 값이 같으면 같은 랜덤값, 다르면 다른 랜덤값)
- rand : uniform(균등분포)하게 랜덤 값을 뽑아줌 (뽑히는 숫자의 횟수가 균등분포)
- randn : gaussian(정규분포)로 랜덤값을 뽑아줌 (뽑히는 숫자의 횟수가 정규분포)
- randint : 정수를 랜덤하게 뽑아줌
- shuffle : 섞어주는 함수
- choice : 여러 개에서 선택해주는 함수

In [70]:
np.random.seed(0)
rd = np.random.rand(10)
rd

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [71]:
rd = np.random.rand(2,5)
rd

array([[0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215]])

In [78]:
np.random.seed(1)
rd = np.random.rand(10)
rd #e~는 exponential = ~제곱
# seed가 정해져 있어서 계속 같은 값이 나옴

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

In [74]:
rd = np.random.rand(2,5)
rd

array([[0.80074457, 0.96826158, 0.31342418, 0.69232262, 0.87638915],
       [0.89460666, 0.08504421, 0.03905478, 0.16983042, 0.8781425 ]])

In [80]:
rdn = np.random.randn(2,5)
rdn

array([[-0.17242821, -0.87785842,  0.04221375,  0.58281521, -1.10061918],
       [ 1.14472371,  0.90159072,  0.50249434,  0.90085595, -0.68372786]])

In [91]:
# randint
np.random.randint(10) #10보다 작은 숫자 생성

3

In [92]:
np.random.randint(3,10) #3에서 9까지의 데이터 나옴

9

In [93]:
np.random.randint(5, 11, (3,3))

array([[5, 5, 7],
       [7, 6, 8],
       [9, 7, 5]])

In [94]:
np.random.randint(5, (3,3)) 

TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'

In [95]:
np.random.randint(5, size=(3,3)) 

array([[0, 1, 1],
       [3, 0, 0],
       [4, 2, 4]])

In [ ]:
# shuffle 로 데이터 순서를 바꿀 수 있음

In [96]:
data = np.random.randint(5, size=(3,3)) 
data

array([[3, 3, 0],
       [3, 4, 3],
       [4, 4, 4]])

In [100]:
np.random.shuffle(data)
data.shape, data # 가장 상단에 있는 것만 shuffle로 바꿔줄 수 있음. 모든 걸 바꾸려면 1열로 만들어서 shuffle하고 reshape

((3, 3), array([[4, 4, 4],
        [3, 4, 3],
        [3, 3, 0]]))

In [102]:
# choice
np.random.choice(5, 10, p=[0.1, 0,  0.3, 0.6, 0]) #0이 10%, 1이 0%, 2가 30%, 3이 60%, 4가 0%의 확률로

array([3, 3, 2, 3, 2, 3, 3, 0, 3, 0], dtype=int64)

In [103]:
data

array([[4, 4, 4],
       [3, 4, 3],
       [3, 3, 0]])

In [104]:
# unique 아 알아들음. 위의 data에서 0이 1번, 3이 4번, 4가 4번 나왔자나
index, count = np.unique(data, return_counts=True)
print(index)
print(count)

[0 3 4]
[1 4 4]


##### stack
- 행렬을 쌓는 것처럼 합치는 방법

In [113]:
na1 = np.arange(6)
na2 = np.arange(6,12)
print(na1, na1.shape)
print(na2, na2.shape)

[0 1 2 3 4 5] (6,)
[ 6  7  8  9 10 11] (6,)


In [112]:
# axis가 0이면 가로로 쌓음
na3 = np.stack((na1,na2))
print(na3, na3.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)


In [114]:
# axis가 0이 아니면 세로로 쌓음. axis default 값이 0임
na4 = np.stack((na1,na2), axis=1)
print(na4, na4.shape)

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]] (6, 2)


In [118]:
na1 = np.random.randint(10, size=(2,3))
na2 = np.random.randint(10, size=(2,3))
print(na1, na1.shape)
print(na2, na2.shape)

[[6 5 1]
 [4 6 0]] (2, 3)
[[6 5 1]
 [2 1 5]] (2, 3)


In [1]:
na3 = np.stack((na1,na2))
print(na3, na3.shape)

NameError: name 'np' is not defined

In [125]:
na4 = np.stack((na1,na2), axis=1)
print(na4, na4.shape)

[[[6 5 1]
  [6 5 1]]

 [[4 6 0]
  [2 1 5]]] (2, 2, 3)


In [126]:
# vstack
# [[0,1,2], [1,2,3], [2,3,4], [3,4,5], [4,5,6]]
ls = []
for idx in range(5):
    ls.append(range(7)[idx:idx+3])
ls

[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [127]:
np.vstack(ls)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [128]:
# hstack
np.hstack(ls)

array([0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

In [130]:
ls = [list(range(7)[idx:idx+3])for idx in range(5)]
ls

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]

In [131]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [132]:
np.arange(5)[:3]

array([0, 1, 2])

In [133]:
np.arange(5)[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

##### concatenate 결합
- 가로결합: 행의 갯수가 같아야 함
- 세로결합: 열의 갯수가 같아야 함

In [135]:
r1 = np.random.randint(10, size=(2,3))
r1

array([[4, 0, 7],
       [8, 9, 5]])

In [136]:
r2 = np.random.randint(10, size=(3,2))
r2

array([[7, 0],
       [9, 3],
       [9, 1]])

In [137]:
r3 = np.random.randint(10, size=(3,3))
r3

array([[4, 4, 6],
       [8, 8, 9],
       [2, 7, 5]])

In [139]:
np.concatenate((r1,r3))

array([[4, 0, 7],
       [8, 9, 5],
       [4, 4, 6],
       [8, 8, 9],
       [2, 7, 5]])

In [141]:
np.concatenate((r1,r3), axis = 1)
#??????

ValueError: all the input array dimensions except for the concatenation axis must match exactly

##### split

In [145]:
r = np.arange(10,20)
r
# array에서 10 앞이 0이라고 보면 됨

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [146]:
r1 = np.split(r, [5])
r1

[array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]

In [147]:
r2 = np.split(r, [2,4,6,8])
r2

[array([10, 11]),
 array([12, 13]),
 array([14, 15]),
 array([16, 17]),
 array([18, 19])]

In [ ]:
# vsplit - 행렬을 수평으로 나눠줌

In [148]:
r = np.random.randint(10, size=(4,6))
r

array([[5, 4, 5, 8, 5, 8],
       [1, 1, 8, 7, 0, 3],
       [4, 2, 0, 3, 5, 1],
       [2, 4, 3, 0, 6, 0]])

In [150]:
r1, r2, r3 = np.vsplit(r, [2,3]) 
print(r1)
print(r2)
print(r3)

[[5 4 5 8 5 8]
 [1 1 8 7 0 3]]
[[4 2 0 3 5 1]]
[[2 4 3 0 6 0]]


In [ ]:
# hsplit - 행렬을 수직으로 나눠줌

In [151]:
r1, r2 = np.hsplit(r, [2]) 
print(r1)
print(r2)

[[5 4]
 [1 1]
 [4 2]
 [2 4]]
[[5 8 5 8]
 [8 7 0 3]
 [0 3 5 1]
 [3 0 6 0]]


##### sort

In [152]:
r1 = np.random.randint(10, size = (3,3))
r1

array([[7, 2, 8],
       [3, 0, 8],
       [4, 2, 9]])

In [153]:
r1.sort() 
r1 # 같은 행 안에서 sorting 됨. 열은 상관 없네. sort는 axis 가 -1이 default임. axis가 0이 아니면 세로로 sorting. 

array([[2, 7, 8],
       [0, 3, 8],
       [2, 4, 9]])

In [154]:
r1.sort(axis=0) # axis를 0으로 하면 가로 sorting
r1

array([[0, 3, 8],
       [2, 4, 8],
       [2, 7, 9]])

In [ ]:
# axis값에 따라서 차원이 하나씩 안으로 들어감 stack에서

In [156]:
np.c_[np.array([1,2,3]), np.array([4,5,6])] #column 으로 합쳐짐

array([[1, 4],
       [2, 5],
       [3, 6]])

In [157]:
np.r_[np.array([1,2,3]), np.array([4,5,6])] #row로 합쳐짐

array([1, 2, 3, 4, 5, 6])

In [ ]:
#근데 얘네보다 stack이랑 concat이 빠름

In [ ]:
# 3차원에서의 axis=0,1,2 예 참고 - 강사님 파일에 있음.  stack에서.