##### Numpy - Calculate

- basic calculate
- broadcasting
- functions
- performance

##### 기본연산

In [1]:
ls = [1,2,3]
ls*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [2]:
ls = [num*3 for num in ls]
ls

[3, 6, 9]

In [4]:
import numpy as np

In [5]:
na = np.array([1,2,3])
na

array([1, 2, 3])

In [7]:
na*3 #모든 요소에 곱하기 3

array([3, 6, 9])

In [8]:
# array 끼리 곱
na1 = np.array([1,2,3])
na2 = np.array([4,5,6])
na1 * na2

array([ 4, 10, 18])

In [10]:
# 비교연산
na1 == 2, na2 > 5

(array([False,  True, False]), array([False, False,  True]))

In [16]:
na1 = np.array(range(1,10))
print(na1)
is3 = na1 % 3 == 0
is3

[1 2 3 4 5 6 7 8 9]


array([False, False,  True, False, False,  True, False, False,  True])

In [17]:
na1[is3]

array([3, 6, 9])

In [20]:
na1[na1 % 2 == 0]

array([2, 4, 6, 8])

##### 브로드캐스팅

In [21]:
na1 = np.arange(12)
na2 = na1.reshape(3,4)
na3 = np.ones((3,4), dtype = int)
print(na1)
print(na2)
print(na3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [22]:
na2 + na3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
na2 + 1 # 모든 요소에 더하기 1 ----> 브로드캐스팅

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
# row에 대한 브로드 캐스팅
na4 = np.arange(4)
print(na4)

[0 1 2 3]


In [25]:
na2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
na2 + na4 # 이것도 일종의 브로드캐스팅

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [28]:
na5 = np.arange(3)
print(na5)

[0 1 2]


In [29]:
na2 + na5 # shape이 중요함

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
# column에 대한 브로드 캐스팅

In [31]:
na5 = np.arange(3)[:, np.newaxis]
na5, na5.shape

(array([[0],
        [1],
        [2]]), (3, 1))

In [32]:
na2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
na2 + na5

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

##### functions
- min, max, argmin, argmax
- sum, mean, median, std, var
- all, any
- quartile
- exp, log

In [34]:
r = np.random.randint(10 ,size = (2,3))
r

array([[2, 0, 7],
       [2, 5, 4]])

In [36]:
# argmin, argmax: index를 출력(위치를 나타냄)
r.min(), r.max(), r.argmin(), r.argmax()

(0, 7, 1, 2)

In [37]:
r.mean() # 평균값

3.3333333333333335

In [39]:
np.sum(r), np.sum(r)/6

(20, 3.3333333333333335)

In [40]:
np.sum(r, axis = 0) #column 더함

array([ 4,  5, 11])

In [41]:
np.sum(r, axis = 1) #row 더함

array([ 9, 11])

In [42]:
r

array([[2, 0, 7],
       [2, 5, 4]])

In [44]:
np.median(r) #중간값 (갯수가 짝수일 경우 가운데 두 값의 평균이라서 소수점이 나오기도 함)

3.0

In [45]:
np.std(r) #표준편차

2.2852182001336816

In [46]:
np.var(r) #변화량, 분산

5.222222222222222

In [47]:
# all - 모든 조건이 True여야 True
# any - 하나의 조건만 True면 True --- like 'or'

In [48]:
n1 = np.array(range(3,8))
n1

array([3, 4, 5, 6, 7])

In [50]:
n2 = n1
n2

array([3, 4, 5, 6, 7])

In [51]:
n3 = np.array([3, 4, 0, 6, 7])
n3

array([3, 4, 0, 6, 7])

In [53]:
n1 == n2, n1 == n3

(array([ True,  True,  True,  True,  True]),
 array([ True,  True, False,  True,  True]))

In [55]:
np.all(n1 == n2), np.all(n1 == n3)

(True, False)

In [56]:
# any
np.any(n1 == n2), np.any(n1 == n3)

(True, True)

In [57]:
n4 = np.array(range(10,15))
print(n4 == n1)
np.any(n1 == n2), np.any(n1 == n3), np.any(n1 == n4)

[False False False False False]


(True, True, False)

In [58]:
np.all(n1 == n4)

False

In [59]:
# 사분위수 e.g. 0~10 중 50%수 면 5 가져옴. 
na = np.arange(101) #가져오는 수는 제외라서 100아니라 101
print(na)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [61]:
np.percentile(na, 25), np.percentile(na, 62)

(25.0, 62.0)

In [62]:
na = np.arange(100, 201) 
print(na)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]


In [63]:
np.percentile(na, 25), np.percentile(na, 62)

(125.0, 162.0)

In [64]:
# 우리나라 1000만 명의 소득 순위를 쭉 나열하고 그 중 20%에 해당하는 사람이 얼마를 버는지 확인하려면 이런 방법 쓸 수 있음

In [65]:
# 지수함수
na = np.arange(1,6)
na

array([1, 2, 3, 4, 5])

In [66]:
np.exp(na)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [67]:
# 로그함수
np.log(na)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

#### 지수함수 로그함수 언제 써? 뭐 데이터의 수치가 너무 작을 때 지수함수 넣어서 뻥튀기 해주면 비교하거나 보기 편하니까. 로그함수는 수치 데이터가 너무 커서 이 스케일을 줄여주고 싶을 때 쓰면 됨

##### 성능 확인

In [69]:
# 10**7개의 리스트에서 3과 5의 배수의 갯수를 찾는 시간

In [72]:
%%time
ls = []
size = int(10E7)
for data in range(size):
    ls.append(data)
len(ls)

Wall time: 1min 31s


In [3]:
%%time
la = np.arange(size)
len(la)

NameError: name 'np' is not defined

In [74]:
%%time
count = 0
for idx in range(len(ls)):
    if (ls[idx] % 3 == 0) or (ls[idx] % 5 == 0):
        count += 1
print(count)

46666667
Wall time: 2min 34s


In [2]:
%%time
count = len(la[la % 3 == 0] | [la % 5 == 0])
count

NameError: name 'la' is not defined

In [5]:
import numpy as np

In [11]:
number = 5

In [35]:
na = np.arange(1,number**2+1).reshape(number,number)

In [36]:
for (i,j) in range(number,number):
    na[i,j] = (i+1)*(j+1)

In [37]:
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
for i in range(number):
    for j in range(number):
        na[i,j] = (i+1)*(j+1)

In [41]:
na

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])